package com.cl.ytsignin.dao.po;

import org.springframework.stereotype.Component;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table depart
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class Depart {
    /** 部门id*/
    private Integer departId;

    /** 部门名称*/
    private String name;

    /** 添加时间*/
    private Date createTime;

    /** 更新时间*/
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.departId
     *
     * @return the value of depart.departId
     *
     * @mbg.generated
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.departId
     *
     * @param departId the value for depart.departId
     *
     * @mbg.generated
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.name
     *
     * @return the value of depart.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.name
     *
     * @param name the value for depart.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.createTime
     *
     * @return the value of depart.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.createTime
     *
     * @param createTime the value for depart.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.updateTime
     *
     * @return the value of depart.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.updateTime
     *
     * @param updateTime the value for depart.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}