package com.cl.ytsignin.dao.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wxuser
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Wxuser {
    /** 唯一的openId*/
    private String openId;

    /** 头像地址*/
    private String avataUrl;

    /** */
    private String city;

    /** */
    private String country;

    /** */
    private Integer gender;

    /** */
    private String language;

    /** */
    private String nickName;

    /** */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.openId
     *
     * @return the value of wxuser.openId
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.openId
     *
     * @param openId the value for wxuser.openId
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.avataUrl
     *
     * @return the value of wxuser.avataUrl
     *
     * @mbg.generated
     */
    public String getAvataUrl() {
        return avataUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.avataUrl
     *
     * @param avataUrl the value for wxuser.avataUrl
     *
     * @mbg.generated
     */
    public void setAvataUrl(String avataUrl) {
        this.avataUrl = avataUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.city
     *
     * @return the value of wxuser.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.city
     *
     * @param city the value for wxuser.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.country
     *
     * @return the value of wxuser.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.country
     *
     * @param country the value for wxuser.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.gender
     *
     * @return the value of wxuser.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.gender
     *
     * @param gender the value for wxuser.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.language
     *
     * @return the value of wxuser.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.language
     *
     * @param language the value for wxuser.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.nickName
     *
     * @return the value of wxuser.nickName
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.nickName
     *
     * @param nickName the value for wxuser.nickName
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxuser.province
     *
     * @return the value of wxuser.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxuser.province
     *
     * @param province the value for wxuser.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }
}