package com.cl.ytsignin.controller.vo;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserVo {
	/**
	 * 用户唯一编号
	 */
	private String id;

	/**
	 * 用户姓名
	 */
	private String name;

	/**
	 * 性别
	 */
	private String sex;

	private String clazzNo;
	private String sID;

	public String getClazzNo() {
		return clazzNo;
	}

	public void setClazzNo(String clazzNo) {
		this.clazzNo = clazzNo;
	}

	public String getsID() {
		return sID;
	}

	public void setsID(String sID) {
		this.sID = sID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.id
	 *
	 * @return the value of user.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.id
	 *
	 * @param id the value for user.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.name
	 *
	 * @return the value of user.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.name
	 *
	 * @param name the value for user.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.sex
	 *
	 * @return the value of user.sex
	 * @mbg.generated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.sex
	 *
	 * @param sex the value for user.sex
	 * @mbg.generated
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}
}