package com.cl.ytsignin.dao.mapper;

import com.cl.ytsignin.dao.po.Depart;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface DepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer departId);

	/**
	 * 获取限制索引范围的depart
	 * @return
	 */
	List<Depart> selectAll(Integer start,Integer limit);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int insert(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int insertSelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    Depart selectByPrimaryKey(Integer departId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Depart record);
}