package com.cl.ytsignin.dao.mapper;

import com.cl.ytsignin.dao.po.Signinrecord;
import org.springframework.stereotype.Component;

@Component
public interface SigninrecordMapper {
	/**
	 * 根据活动id和openId查询记录
	 * @param eventId
	 * @param openId
	 * @return
	 */
	Signinrecord selectUnique(Integer eventId,String openId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int insert(Signinrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int insertSelective(Signinrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    Signinrecord selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Signinrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Signinrecord record);
}