package com.cl.ytsignin.dao.mapper;

import com.cl.ytsignin.dao.po.Signevent;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SigneventMapper {
	/**
	 * 根据openId来查找签到活动记录
	 * @param openId
	 * @return
	 */
	List<Signevent> selectByopenId(String openId);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signevent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signevent
     *
     * @mbg.generated
     */
    int insert(Signevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signevent
     *
     * @mbg.generated
     */
    int insertSelective(Signevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signevent
     *
     * @mbg.generated
     */
    Signevent selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signevent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Signevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signevent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Signevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signevent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Signevent record);
}