package com.cl.ytsignin.dao.mapper;

import com.cl.ytsignin.controller.vo.SigneventVo;
import com.cl.ytsignin.controller.vo.SignrecordVo;
import com.cl.ytsignin.controller.vo.StudentNoneSignrecordVo;
import com.cl.ytsignin.dao.po.Signevent;
import com.cl.ytsignin.dao.po.Signinrecord;
import io.swagger.models.auth.In;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SigninrecordMapper {
	/**
	 * 删除某openId下的所有限定班级的签到记录
	 * @param openId
	 * @return
	 */
	int deleteByOpenIdWithLock(String openId);
	/**
	 * 根据活动id查询已经签到的人员嗯
	 * @param eventId
	 * @return
	 */
	List<StudentNoneSignrecordVo> selectSignUser(Integer eventId);
	/**
	 * 根据班级编号和签到活动编号查询没有签到的学生
	 * @param eventId
	 * @param clazzNo
	 * @return
	 */
	List<StudentNoneSignrecordVo> selectNoneSignStudent(Integer eventId, String clazzNo);
	/**
	 * 根据活动查询
	 * @param eventId
	 * @return
	 */
	List<SignrecordVo> selectByEventId(Integer eventId);
	/**
	 * 根据活动id和openId查询记录
	 * @param eventId
	 * @param openId
	 * @return
	 */
	Signinrecord selectUnique(Integer eventId,String openId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int insert(Signinrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int insertSelective(Signinrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    Signinrecord selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Signinrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signinrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Signinrecord record);
}