package com.cl.ytsignin.dao.mapper;

import com.cl.ytsignin.dao.po.User;
import org.springframework.stereotype.Component;

@Component
public interface UserMapper {
	/**
	 * 更新某个id的值为指定的openId
	 *
	 * @param id
	 * @param openId
	 * @return
	 */
	int updateOpenIdById(String openId, String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbg.generated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbg.generated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbg.generated
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(User record);
}