package com.cl.ytsignin.dao.mapper;

import com.cl.ytsignin.controller.vo.UserVo;
import com.cl.ytsignin.dao.po.User;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface UserMapper {
	/**
	 * 查询所有班级编号
	 */
	List<String> selectAllClazz();
	/**
	 * 通过设置openId为null来解绑
	 * @param openId
	 * @return
	 */
	int unBindOpenId(String openId);
	/**
	 * 根据openId查询Vo对象
	 * @param openId
	 * @return
	 */
	UserVo selectVoByOpenID(String openId);
	/**
	 * 根据学号来取出一个用户
	 * @param sID
	 * @return
	 */
	User selectBysID(String sID);
	/**
	 * 根据openId来查找用户
	 * @param openId
	 * @return
	 */
	User selectByOpenId(String openId);
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

	/**
	 * 插入，重复就更新
	 * @param record
	 * @return
	 */
	int insertWithUpdate(User record);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
}