package com.cl.ytsignin.dao.mapper;

import com.cl.ytsignin.dao.po.Wxuser;
import org.springframework.stereotype.Component;

@Component
public interface WxuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int insert(Wxuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int insertSelective(Wxuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    Wxuser selectByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Wxuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wxuser record);
}